### PR TITLE
Add backup flags to AuthenticatorData

### PR DESCRIPTION
**Pull request by JammyStuff**
In the working draft of the specification, bits 3 and 4 of the flags field of the Authenticator Data structure now correspond to the backup eligibility and backup state of the credential respectively.

https://w3c.github.io/webauthn/#sctn-authenticator-data

### CODE REVIEW

**Comment by tanguilp** [comment]
Thanks for the PR. At first glance it looks good!

But should we include extensions that are still in draft in this library? Looks like you need it now. I'd be interested to understand why. Are they some authenticators that already implement it? Would implementing it on a branch be ok until the draft is approved?

**Comment by JammyStuff** [comment]
Happy to keep it in a branch until WebAuthn Level 3 is published if that is preferred. Passkeys on iOS/macOS that are synced to your Apple ID seem to already be setting these flags (unsure about Android), as well as passkeys in 1Password, so there is some use of this in the wild already.

An example of the use case for this would be if you wanted to warn a user that they should add a second authenticator to avoid account lockout, but skipping this warning when the backup state is true. Yubico's passkey demo (https://passkey.org/) appears to do this, but I don't think the source is available so am not certain they are doing it using these flags.

**Comment by tanguilp** [comment]
Looks like iOS at least indeed supports it. There's little risk it'll be removed IMO, but token binding is being removed from level3 so who knows. Let me think about it a few more days.

I'm also wondering if we could rename the fields to bring more clarity:
- `flag_backup_eligibility` → `flag_backup_eligibile` (https://w3c.github.io/webauthn/#backup-eligibility uses both variants)
- `flag_backup_state` → `flag_is_backed_up` or `flag_credential_backed_up`? Doesn't sound great though. Any other idea is welcome

**Comment by JammyStuff** [comment]
Sure, I've also now had a chance to test using an Android device and it seems those flags are also set there now (provided you are running an up-to-date version of Chrome).

For renaming, I'd gone with the names given in the flags field of the spec, but if you are happy for us to use better names, that's great! I definitely prefer `flag_backup_eligible` over `flag_backup_eligibility`. For the backup state, it looks like Duo's py_webauthn uses `credential_backed_up` and Yubico's python-fido2 uses `is_backed_up`, so either option you gave sounds good. I think `flag_credential_backed_up` probably fits better with the names of the other flags in this library?

**Comment by tanguilp** [comment]
> Sure, I've also now had a chance to test using an Android device and it seems those flags are also set there now (provided you are running an up-to-date version of Chrome).

Alright, then we can include it in Wax directly.

> For renaming, I'd gone with the names given in the flags field of the spec, but if you are happy for us to use better names, that's great! I definitely prefer flag_backup_eligible over flag_backup_eligibility. For the backup state, it looks like Duo's py_webauthn uses credential_backed_up and Yubico's python-fido2 uses is_backed_up, so either option you gave sounds good. I think flag_credential_backed_up probably fits better with the names of the other flags in this library?

I have a preference for `flag_backup_eligible` and `flag_credential_backed_up` as well. Willing to update the PR? :)

**Comment by JammyStuff** [comment]
> I have a preference for flag_backup_eligible and flag_credential_backed_up as well. Willing to update the PR? :)

Yup! I'll try and get an update pushed in a few hours after I finish work.

**Comment by tanguilp** [comment]
Wax 0.6.2 has been published. Thanks for contributing!

**Pull request merged**
